### PR TITLE
Fix typo of "维度" and add link of the md files

### PR DESCRIPTION
**Pull request by Spacebody**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*
#353 
Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

**Code formatting**

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by yuansx** [comment]
你这个PR把最后一行删了，加回来吧。另外麻烦顺便把英文文档同步更改一下，谢谢

**Comment by Spacebody** [comment]
@yuansx 好的

**Comment by Spacebody** [comment]
@yuansx 能否麻烦确认一下 tars_config.md 文件的位置，我找不到。

**Comment by yuansx** [comment]
https://github.com/TarsCloud/TarsFramework/tree/master/docs

**Comment by Spacebody** [comment]
@yuansx 好了。英文版也更新好了。 #363

**Comment by yuansx** [comment]
好的，谢谢你的支持！！

**Comment by Spacebody** [comment]
@yuansx 不客气。

**Pull request merged**
